from GetHits import getAllHits

toAddress = "minghuig@gmail.com"
subreddits = [
"AnimalPorn",
"AnimalsBeingBros",
"AnimalsBeingJerks",
"AskReddit",
"askscience",
"AskWomen",
"asoiaf",
"aww",
"babyelephantgifs",
"bears",
"bearsdoinghumanthings",
"bestof",
"birdpics",
"books",
"BurningMan",
"CampingandHiking",
"changemyview",
"dogs",
"EarthPorn",
"explainlikeimfive",
"foxes",
"funny",
"gamedev",
"germanshepherds",
"gifs",
"GradSchool",
"husky",
"IAmA",
"InternetIsBeautiful",
"itookapicture",
"LadyBoners",
"legaladvice",
"mountaingoats",
"movies",
"pics",
"primatology",
"relationships",
"science",
"sex",
"shittyaskscience",
"ShittyEarthPorn",
"shittyprogramming",
"solotravel",
"somethingimade",
"todayilearned",
"travel",
"TwoXChromosomes",
"videos",
"woahdude",
"WritingPrompts",
"WTF",
"zoology"
]

getAllHits(subreddits, toAddress)
